stages:

  - flutter-test
  - flutter-build


# Flutter Jobs
Flutter Test:
  stage: flutter-test
  image: cirrusci/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter test
  artifacts:
    name: "flutter-test-results"
    when: always
    expire_in: 1 week
    paths:
      - coverage/
  only:
    - frontend

Flutter Build:
  stage: flutter-build
  image: cirrusci/flutter:stable
  before_script:
    - flutter pub get
  script:
    - flutter build web
  artifacts:
    name: "flutter-build-artifacts"
    expire_in: 1 week
    paths:
      - build/web/
  only:
    - frontend
